services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    volumes:
      - db_data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
